### ISSUE TITLE
EPIC: Nawerk VNG Hackathon

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/mijn-services#17]
```[tasklist]
### VrijBRP notificaties
- [ ] Mapping naar vul service testen & laten maken door Conduction
- [ ] Testen OMC met Conduction mappings
- [ ] Checken hele keten (formulier -> ZGW Notificaties -> VulService/OMC -> Notify)
```

```[tasklist]
### Woweb notificaties
- [x] Ombouwen vul service voor aanmaken contactpersoon in openklant
- [x] Ombouwen vul service voor opslaan partij in betrokkene veld rol
- [ ] Testen met nieuwe release OMC obv betrokkene veld
```

**Comment by marnixdessing** [comment]
Woweb productie taken staan in een eigen epic. Voor VrijBRP notificatis gaan we nog een evaluatie inplannen. Dit epic wordt gesloten.
