### ISSUE TITLE
[mijn-services] Zorgen dat notificatie component op accp werkt

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/mijn-services#18]
```[tasklist]
### Tasks
- [x] Fixen RabbitMQ communicatie tussen containers
- [ ] Updaten wanneer er een fix is voor open-notificaties create webhook subscription
- [ ] Configureren self subscription
```

**Comment by marnixdessing** [comment]
Ook nog even handmatig testen of dit nu echt werkt (notificatie delivery)

**Comment by marnixdessing** [comment]
Niet alle notificaties worden verstuurd vanuit open-zaak. Even uitzoeken waarom. Ik vermoed omdat de redis db nummers gedeeld waren tussen open-zaak en open-notificaties. Het gedrag was ook een beetje random (soms wel een notificatie van een rol/status/zaak en soms niet, in verschillende samenstellingen).

**Comment by marnixdessing** [comment]
Dat probleem is verholpen door de redis DB nummers aan te passen.

**Comment by marnixdessing** [comment]
Notificaties werken gewoon, alleen de self-subscription kan niet gepubliseerd worden en de configuratie test pagina (/view-config) kan niet worden geladen. Hiervoor moet een fix gedaan worden en die staat uit bij open-notificaties geloof ik. Ik sluit dit issue daarom maar gewoon, voor onze doeleinden kunnen we de accp omgeving gebruiken zoals we willen.
