### ISSUE TITLE
EPIC: vanuit VIP notificeren (deel A)

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/mijn-services#57]
De afdeling wil alleen bij een taak een notificatie versturen, niet bij een statuswijziging van een zaak. De zaak is te volgen in Mijn Nijmegen en melding van een statuswijziging voegt niets toe. 
De notificatie bij een taak kan via e-mail of sms plaatsvinden. Beide mogen toegepast worden.

Daar waar nu In het proces een e-mail verstuurd wordt (bijvoorbeeld bij een ontvangstbevestiging) mag dit ook via notify verstuurd worden. Verwachting is wel dat notify vanuit het domein Nijmegen mails verstuurd. Er wordt vanuit gegaan dat dit alleen een e-mail is en geen sms. 

Er kan in de toekomst ook gekeken wordt of er een sms verstuurd kan worden, maar dan moet aan de voorkant in het formulier opgenomen worden wat het voorkeurkanaal van de Nijmegenaar is.

```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1239
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1306
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1308
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1322
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1323
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1307
- [ ] https://github.com/GemeenteNijmegen/mijn-nijmegen/issues/1311
- [ ] [VIP Notify] Regisratie service in productie uitrollen en koppelen met VIP
- [ ] [VIP Notify] Tests met afdeling plannen
- [ ] [VIP Notify] Credentials delen met VIP om het OMC aan NotifyNL productie te koppelen
```
